[package]
name = "farm"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[dependencies]
bevy = { version = "0.19.0", features = ["wayland", "bevy_dev_tools"] }
bevy-inspector-egui = { version = "0.37.0" }
bevy_embedded_assets = { version = "0.16.0" }
bevy_asset_loader = { version = "0.27.0" }
avian2d = { version = "0.7.0", features = ["simd", "bevy_picking"] }
